### ISSUE TITLE
Typo - wrong build command 

### ISSUE THREAD

**Issue by djukela17** [veniamin-ilmer/go-vs-rust-primes#2]
Hi,

Sorry for bringing this in since it is not really important, but I noticed you pasted the go build command twice in the **Attempt 3: Slices**. 
- once for the go file properly
- another time for the rust file, which should have the cargo build command included. 

You can see it in the screenshot below.

![screenshot from 2018-10-04 14-16-10](https://user-images.githubusercontent.com/32014515/46473370-332d2b00-c7e0-11e8-8296-330014bc60df.png)

**Comment by veniamin-ilmer** [comment]
Thanks, fixed.
